#!/bin/bash

############################################################
## YOUR VALUES ##
#################

## Specify the version of 'master' if anything other than
## 'upcoming'. To disable this checking, change this value
## to 'master' instead:
CURRENTMASTER="v5.0"

############################################################
## BEGIN SCRIPT ##
##################

SOURCEISMASTER=0

TMPDIR=/tmp/newbranch$$

## Check for provided parameter:
PARAMETER=$1

## Parse user-provided parameter and determine what to do:
if [[ -z $PARAMETER || ! -z $2 ]]; then
   echo -e "\nERROR: Either no or 2+ parameters provided. You must provide ONE"
   echo -e "     MDB version like: v4.2.3, v4.0.14, etc"
   echo -e "     Exiting ...\n"
   exit;
elif [ `echo $PARAMETER | sed 's%^v%%g' | egrep -c '^[0-9]\.[0-9]\.[0-9]{1,2}$'` -lt 1 ]; then
   echo -e "\nERROR: Invalid MDB  version provided."
   echo -e "       Must be ONE MDB version like: v4.2.3, v4.0.14, etc"
   echo -e "       Exiting ...\n"
   exit;
else
   VERS=`echo $PARAMETER | sed 's%^v%%g'`
   MAJORVERS=`echo $VERS | awk -F'.' '{print $1"."$2}'`

   ## Determine if provided VERS requires 'master' as source branch:
   CURRENTMASTER=`echo $CURRENTMASTER | sed 's%^v%%g'`
   if [ $CURRENTMASTER == $MAJORVERS ]; then
      SOURCEISMASTER=1
   fi
fi

mkdir -p $TMPDIR

cd $TMPDIR
git clone git@github.com:mongodb/docs.git
cd docs

## Source new minor release branch from appropriate
## major release branch:
if [ $SOURCEISMASTER == 1 ]; then
   git checkout master
   git pull --rebase
   git push origin master:v$VERS
else
   git checkout v$MAJORVERS
   git pull --rebase
   git push origin v$MAJORVERS:v$VERS
fi

rm -rf $TMPDIR



